version: '3.5'

x-app: &default-app
  build: 
      context: .
  networks:
    - RinhaNetwork
  deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

services:

  api01:
    <<: *default-app
    ports:
      - 8081:8080

  api02:
    <<: *default-app
    ports:
      - 8082:8080

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    networks:
      - RinhaNetwork
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "75MB"

  db:
    image: postgres
    hostname: db
    ports:
      - 5432:5432
    networks:
      - RinhaNetwork
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: RinhaDB
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "275MB"

# volumes:
#   pgsql:

networks:
  RinhaNetwork:
    driver: bridge