version: '3.5'

x-app: &default-app
  build: 
      context: .
  networks:
    - RinhaNetwork

services:

  app01:
    <<: *default-app
    ports:
      - 8081:8080

  app02:
    <<: *default-app
    ports:
      - 8082:8080

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999" 
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.17"
  #         memory: "10MB"

  db:
    image: postgres
    hostname: db
    ports:
      - 5432:5432
    networks:
      - RinhaNetwork
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: RinhaDB

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - RinhaNetwork

# volumes:
#   pgsql:

networks:
  RinhaNetwork:
    driver: bridge